export interface PeriodStats {
  spend: number;
  impressions: number;
  clicks: number;
  conversions: number;
  revenue: number;
  roas: number;
  ctr: number;
}

export interface DailyDataPoint {
  date: string; // yyyy-mm-dd
  spend: number;
  impressions: number;
  clicks: number;
  conversions: number;
  revenue: number;
  ctr: number;
  cpc: number;
  cpm: number;
  poas: number; // revenue / spend (GetKlar attributed)
}

export interface Campaign {
  id: string;
  name: string;
  platform: string; // e.g. 'meta', 'google', 'tiktok', 'unknown'
  spend: number;
  impressions: number;
  clicks: number;
  conversions: number;
  revenue: number;
  roas: number;
  ctr: number;
  cpc: number;
  cpm: number;
  dailyData: DailyDataPoint[];
  period: {
    current: PeriodStats;
    previous: PeriodStats;
  };
  bucket: BucketType;
  // Optional field, generated by AI
  aiStatus?: '🟢 Performing' | '🟡 Watch' | '🔴 Underperforming';
}

export type BucketType = 'switzerland' | 'retention' | 'newcustomer' | 'branding';

export const BUCKET_LABELS: Record<BucketType, string> = {
  switzerland: '🇨🇭 Switzerland',
  retention: '🔁 Retention / BOFU',
  newcustomer: '🚀 New Customer Acquisition',
  branding: '📣 Branding',
};

export interface Insight {
  id: string;
  type: '💡 Potential' | '✅ Improvement' | '⚠️ Deterioration';
  message: string;
  campaignId?: string;
}

export interface GetKlarData {
  campaigns: Campaign[];
}
