export interface PeriodStats {
  spend: number;
  impressions: number;
  clicks: number;
  conversions: number;
  grossRevenue: number;
  netRevenue: number;
  roas: number; // grossRevenue / spend = POAS
  ctr: number;
}

export interface DailyDataPoint {
  date: string; // yyyy-mm-dd
  spend: number;
  impressions: number;
  clicks: number;
  conversions: number;
  grossRevenue: number; // grossRevenue/spend = POAS
  netRevenue: number;   // netRevenue/spend  = aPOAS
  ctr: number;
  cpc: number;
  cpm: number;
  poas: number;  // grossRevenue / spend
  apoas: number; // netRevenue  / spend
}

export interface Campaign {
  id: string;
  name: string;
  platform: string;
  spend: number;
  impressions: number;
  clicks: number;
  conversions: number;
  grossRevenue: number;
  netRevenue: number;
  roas: number; // POAS = grossRevenue / spend
  ctr: number;
  cpc: number;
  cpm: number;
  dailyData: DailyDataPoint[];
  period: {
    current: PeriodStats;
    previous: PeriodStats;
  };
  bucket: BucketType;
  // Optional field, generated by AI
  aiStatus?: '🟢 Performing' | '🟡 Watch' | '🔴 Underperforming';
}

export type BucketType = 'switzerland' | 'retention' | 'newcustomer' | 'branding';

export type DateRange = '7v7' | '14v14' | '30d';
export type PlatformFilter = 'all' | 'meta' | 'google';
export type StatusFilter = 'all' | 'active' | 'paused';
export type SortBy = 'highest-spend' | 'lowest-poas';

export const BUCKET_LABELS: Record<BucketType, string> = {
  switzerland: '🇨🇭 Switzerland',
  retention: '🔁 Retention / BOFU',
  newcustomer: '🚀 New Customer Acquisition',
  branding: '📣 Branding',
};

export interface Insight {
  id: string;
  type: '💡 Potential' | '✅ Improvement' | '⚠️ Deterioration';
  message: string;
  campaignId?: string;
}

export interface GetKlarData {
  campaigns: Campaign[];
}
